# Generated by Django 5.0.6 on 2024-07-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_homeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('decription', models.TextField(blank=True)),
                ('project_photo', models.ImageField(upload_to='images/projects_img')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='homeinfo',
            options={'verbose_name_plural': 'Home Info'},
        ),
    ]
