# Generated by Django 5.0.6 on 2024-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"verbose_name_plural": "Experience"},
        ),
        migrations.RemoveField(
            model_name="experience",
            name="company",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="end_year",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="position",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="start_year",
        ),
        migrations.AddField(
            model_name="experience",
            name="Duration",
            field=models.CharField(blank=True, default="ok", max_length=100),
        ),
        migrations.AddField(
            model_name="experience",
            name="Company",
            field=models.CharField(blank=True, default="ok", max_length=100),
        ),
        migrations.AddField(
            model_name="experience",
            name="Position",
            field=models.CharField(blank=True, default="ok", max_length=100),
        ),
    ]
