# Generated by Django 5.0.6 on 2024-07-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0008_about_tech_stack"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="tech_stack",
        ),
    ]
